---
  reference:
    genepanels:
      checksum: 5f1b56029a93466747e34c1288e3965b   
      path: poirot/config/gene_panels/genepanels_WGS.list
      type: file
      url: file:poirot_config/config/gene_panels/genepanels_WGS.list
    Amyloidos:
      path: poirot/config/gene_panels/Amyloidos.list
      checksum: a96c0cdf2336449c4eddcac5e23ab78a
      type: file
      url: file:poirot_config/config/gene_panels/Amyloidos.list
    Arytmier:
      path: poirot/config/gene_panels/Arytmier.list
      checksum: fc4781e323c2ca32cd5279c3913169ce
      type: file
      url: file:poirot_config/config/gene_panels/Arytmier.list
    Ataxi:
      path: poirot/config/gene_panels/Ataxi_v5.list
      checksum: f7d106d9fe174d58c3f7fbec35fcfe4b
      type: file
      url: file:poirot_config/config/gene_panels/Ataxi_v5.list
    Bindvav:
      path: poirot/config/gene_panels/Bindvav.list
      checksum: d36801159fe163411831938bb697191a
      type: file
      url: file:poirot_config/config/gene_panels/Bindvav.list
    Bred_skelettdysplasi:
      path: poirot/config/gene_panels/Bred_skelettdysplasi.list
      checksum: aae368d0d61aa1a1ddfb446d34c3ae40
      type: file
      url: file:poirot_config/config/gene_panels/Bred_skelettdysplasi.list
    Bred_NMD_v1:
      path: poirot/config/gene_panels/Bred_NMD_v1.list
      checksum: 6f4780740db5b0a6b4efcf9dbccbecd0
      type: file
      url: file:poirot_config/config/gene_panels/Bred_NMD_v1.list
    Cadasil:
      path: poirot/config/gene_panels/Cadasil.list
      checksum: de698fc0d599d9750bf31ec9af4295db
      type: file
      url: file:poirot_config/config/gene_panels/Cadasil.list
    Cerebrala_smakarlssjukdomar:
      path: poirot/config/gene_panels/Cerebrala_smakarlssjukdomar.list
      checksum: 78a45a896eda13d60177f2ee86954773
      type: file
      url: file:poirot_config/config/gene_panels/Cerebrala_smakarlssjukdomar.list
    ChiCaP:
      path: poirot/config/gene_panels/ChiCaP.list
      checksum: d11a4edabfe086ea7ba854e3314dca82
      type: file
      url: file:poirot_config/config/gene_panels/ChiCaP.list
    DSD:
      path: poirot/config/gene_panels/DSD.list
      checksum: 9e0f1a9913206f5d1f1c7ae60cb79930
      type: file
      url: file:poirot_config/config/gene_panels/DSD.list
    Dystoni:
      path: poirot/config/gene_panels/Dystoni.list
      checksum: 2cc6e32c0bbb44a6800334145fdabee2
      type: file
      url: file:poirot_config/config/gene_panels/Dystoni.list
    EBS:
      path: poirot/config/gene_panels/EBS.list
      checksum: bb30140ffa78883db731837dd57b4a11
      type: file
      url: file:poirot_config/config/gene_panels/EBS.list
    Ektodermal_dysplasi:
      path: poirot/config/gene_panels/Ektodermal_dysplasi.list
      checksum: 6d3957d41880cb1a9fdccf9adff01e25
      type: file
      url: file:poirot_config/config/gene_panels/Ektodermal_dysplasi.list
    Endokrin:
      path: poirot/config/gene_panels/Endokrin.list
      checksum: 125788f7519875ecda3e8f83e364257b
      type: file
      url: file:poirot_config/config/gene_panels/Endokrin.list
    Epidermolysis_bullosa:
      path: poirot/config/gene_panels/Epidermolysis_bullosa.list
      checksum: 4e242f5367a9cd8b9022a6da653dd4e6
      type: file
      url: file:poirot_config/config/gene_panels/Epidermolysis_bullosa.list
    Epilepsi:
      path: poirot/config/gene_panels/Epilepsi.list
      checksum: 4d562495d83a930d05cbe603947fa185
      type: file
      url: file:poirot_config/config/gene_panels/Epilepsi.list
    Hematologi:
      path: poirot/config/gene_panels/Hematologi.list
      checksum: f8e62121cef4930c3e29bb0648b60e1d
      type: file
      url: file:poirot_config/config/gene_panels/Hematologi.list
    Hereditar_hypofystumorpanel:
      path: poirot/config/gene_panels/Hereditar_hypofystumorpanel.list
      checksum: f6cf1866fc38916ff30cbdf7172d2144
      type: file
      url: file:poirot_config/config/gene_panels/Hereditar_hypofystumorpanel.list
    H_feokromocytom_paragangliom:
      path: poirot/config/gene_panels/H_feokromocytom_paragangliom.list
      checksum: f8289a8ae8603e3c94e1b9df9906112c
      type: file
      url: file:poirot_config/config/gene_panels/H_feokromocytom_paragangliom.list
    Horsel:
      path: poirot/config/gene_panels/Horsel.list
      checksum: 9f86dfb6fcbe752052957a769f60690b
      type: file
      url: file:poirot_config/config/gene_panels/Horsel.list
    HSP:
      path: poirot/config/gene_panels/HSP.list
      checksum: 981b84978187f82fdaa9190a8ed0eb12
      type: file
      url: file:poirot_config/config/gene_panels/HSP.list
    Hyperlipidemi_v1:
      path: poirot/config/gene_panels/Hyperlipidemi_v1.list
      checksum: a952c3e9e3789958f01585984a5742d2
      type: file
      url: file:poirot_config/config/gene_panels/Hyperlipidemi_v1.list
    Hyperparatyreoidism:
      path: poirot/config/gene_panels/Hyperparatyreoidism.list
      checksum: e96cc9a6b37069dab17ca2264b0d531d
      type: file
      url: file:poirot_config/config/gene_panels/Hyperparatyreoidism.list
    Iktyos:
      path: poirot/config/gene_panels/Iktyos.list
      checksum: 6725b1fab73df584a85438c26555c4ce
      type: file
      url: file:poirot_config/config/gene_panels/Iktyos.list
    Immun:
      path: poirot/config/gene_panels/Immun.list
      checksum: 3893f0bb9eb20754ef8dc471a550a4ca 
      type: file
      url: file:poirot_config/config/gene_panels/Immun.list
    Kardio:
      path: poirot/config/gene_panels/Kardio.list
      checksum: 761fdf007fee2f2f4b45b37f8ae81a3e
      type: file
      url: file:poirot_config/config/gene_panels/Kardio.list
    Kraniosynostos:
      path: poirot/config/gene_panels/Kraniosynostos.list
      checksum: 1aec2b03e5e73bd31cb9d3c63bfdea5d
      type: file
      url: file:poirot_config/config/gene_panels/Kraniosynostos.list
    MODY_lipodystrophy:
      path: poirot/config/gene_panels/MODY_lipodystrophy.list 
      checksum: eea351479f7c2ad321211c64031318d2
      type: file
      url: file:poirot_config/config/gene_panels/MODY_lipodystrophy.list 
    Neuromuskular:
      path: poirot/config/gene_panels/Neuromuskular_v2.list
      checksum: 9e06fa9da18ce37c802292ace038b6ee
      type: file
      url: file:poirot_config/config/gene_panels/Neuromuskular_v2.list
    Neuropati:
      path: poirot/config/gene_panels/Neuropati_v2.list
      checksum: 81caf48af55689bc6553951a4bbd6263 
      type: file
      url: file:poirot_config/config/gene_panels/Neuropati_v2.list
    Njurcancer:
      path: poirot/config/gene_panels/Njurcancer.list
      checksum: 90d142247c4167d3a92a85094fe4c4e5
      type: file
      url: file:poirot_config/config/gene_panels/Njurcancer.list
    Njursjukdomar:
      path: poirot/config/gene_panels/Njursjukdomar.list
      checksum: 0cb58cfe8559ad9ab55c7c1f1730966b
      type: file
      url: file:poirot_config/config/gene_panels/Njursjukdomar.list
    OI_och_benskorhet:
      path: poirot/config/gene_panels/OI_och_benskorhet.list
      checksum: 282adab72f938e2aa45d35496f75b386
      type: file
      url: file:poirot_config/config/gene_panels/OI_och_benskorhet.list
    Okular_albinism:
      path: poirot/config/gene_panels/Okular_albinism.list
      checksum: fc8dbc18916caf5fd1b9d63d46021ba9
      type: file
      url: file:poirot_config/config/gene_panels/Okular_albinism.list
    Optikus_atrofi:
      path: poirot/config/gene_panels/Optikus_atrofi.list
      checksum: 3efaa8f0fc7ed03ea8106ce9b494068c
      type: file
      url: file:poirot_config/config/gene_panels/Optikus_atrofi.list
    Pachyonychia_congenita:
      path: poirot/config/gene_panels/Pachyonychia_congenita.list
      checksum: 4c049ba63a0d4ac590909dbf2fe46715
      type: file
      url: file:poirot_config/config/gene_panels/Pachyonychia_congenita.list
    PCD:
      path: poirot/config/gene_panels/PCD.list
      checksum: 18c4a440496f392c1a445fac290c80e3
      type: file
      url: file:poirot_config/config/gene_panels/PCD.list
    Periodisk_feber:
      path: poirot/config/gene_panels/Periodisk_feber.list
      checksum: f24c13edfeefa3d07849da66fd100756
      type: file
      url: file:poirot_config/config/gene_panels/Periodisk_feber.list
    Periodisk_paralys:
      path: poirot/config/gene_panels/Periodisk_paralys.list
      checksum: 46f5f16520bd716c8571775bc28a5731
      type: file
      url: file:poirot_config/config/gene_panels/Periodisk_paralys.list
    PPK_och_erytrodermi:
      path: poirot/config/gene_panels/PPK_och_erytrodermi.list
      checksum: 388b525609bb6f1313506aad7e3bb6a0
      type: file
      url: file:poirot_config/config/gene_panels/PPK_och_erytrodermi.list
    Rasopatier:
      path: poirot/config/gene_panels/Rasopatier.list
      checksum: 94f6141811627009253a138d67bb121b
      type: file
      url: file:poirot_config/config/gene_panels/Rasopatier.list
    Retinal_degeneration:
      path: poirot/config/gene_panels/Retinal_degeneration.list
      checksum: fe0dabacff6a0e8144c9373eb910a85f
      type: file
      url: file:poirot_config/config/gene_panels/Retinal_degeneration.list
    Schwannomatos_och_menigiom:
      path: poirot/config/gene_panels/Schwannomatos_och_menigiom.list
      checksum: 77a3004859f8002031fe8a773b9c5669
      type: file
      url: file:poirot_config/config/gene_panels/Schwannomatos_och_menigiom.list
    Sotos:
      path: poirot/config/gene_panels/Sotos.list
      checksum: d4abc6e1e442ee911cb672f6d5aafec3
      type: file
      url: file:poirot_config/config/gene_panels/Sotos.list
    Trombocytopenier:
      path: poirot/config/gene_panels/Trombocytopenier.list
      checksum: 9f574a0896d2190f4382749091f5fe75
      type: file
      url: file:poirot_config/config/gene_panels/Trombocytopenier.list
    Wilms:
      path: poirot/config/gene_panels/Wilms.list
      checksum: 302676d7303ecbae1ff08211cc19f34f
      type: file
      url: file:poirot_config/config/gene_panels/Wilms.list
