--- 
  mt_reference:
    Homo_sapiens_assembly38.chrM.fasta:
      checksum: fec5eec2086dba60eb82fc0b975d80d9
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta
    Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta:
      checksum: 43293e2272acb908db29099cd0f9ebc5
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta
    blacklist_sites.hg38.chrM.bed:
      checksum: 9d19d05152c50d7cd4ac3647c8c4dfd9
      path: poirot/gatk_mito/blacklist_sites.hg38.chrM.bed
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/blacklist_sites.hg38.chrM.bed
    ShiftBack.chain:
      checksum: a65673402f6dce44c7acc449efa017d6
      path: poirot/gatk_mito/gatk_mito/ShiftBack.chain
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/ShiftBack.chain
    non_control_region.chrM.interval_list:
      checksum: d2e36c54427e83e140cad5a2d0bbf045
      path: poirot/gatk_mito/gatk_mito/non_control_region.chrM.interval_list
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/non_control_region.chrM.interval_list
    control_region_shifted.chrM.interval_list:
      checksum: 53ae9360e3657cd9a82987771cfe8ee4
      path: poirot/gatk_mito/gatk_mito/control_region_shifted.chrM.interval_list
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/control_region_shifted.chrM.interval_list
      
  mt_bwa:
    amb:
      checksum:  6749f645487281112c254ab829ea048c
      path: poirot/gatk_mito/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.amb
    ann: 
      checksum: 546a1bf297c7da3d47af1accbffa5dbb
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.ann
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.ann
    bwt:
      checksum: 96337a6d9dc0d7afc562fee8b1afb673
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.bwt
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.bwt
    pac:
      checksum: ecbea80d481b6e8e70da3f464b977d91
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.pac
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.pac
    sa:
      checksum: 7c06a2c0b4f23e785e2f85383b9d1317
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.sa
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.sa

  mt_shifted_bwa:
    amb:
      checksum: 1b6323cb5a4bc2f53730cebcb19b1768
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.amb
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.amb
    ann:
      checksum: 546a1bf297c7da3d47af1accbffa5dbb
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.ann
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.ann
    bwt:
      checksum: e33bdaa2957f3a2568106612f8ab508d
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.bwt
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.bwt
    pac:
      checksum: d82fcfe5da63fbea0173bb7878121768
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.pac
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.pac
    sa:
      checksum: 63e2ea06ee93ffbc324695613cff4bc5
      path: poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.sa
      type: file
      url: file:/beegfs-storage/data/ref_data/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.sa

