---

  reference:
    fasta:
      checksum: e433a4bc249c92feba4805ac011f0e2d
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta
    fasta_index:
      checksum: a44cb7b437c4d34a78047d4d42519f3f
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai
    design_bed:
      checksum: 5b0df2472fd0880aad8e85c583a97232
      path: poirot/homo_sapiens.hg38.wgs.bed
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/homo_sapiens.hg38.wgs.bed
    exome_bed:
      checksum: f8a920a0983b7fe9998be30d5ee18810
      path: poirot/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed
      type: file
      url: file:/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed
    exome_intervals:
      checksum: bd61ce7c4d8a7ed0fc528672f86943a8
      path: poirot/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list
      type: file
      url: file:/data/ref_data/wp3/hastings/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list
    sites:
      checksum: 14cc588a271951ac1806f9be895fb51f
      path: poirot/Homo_sapiens_assembly38.k:wqnown_indels.vcf.gz
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/Homo_sapiens_assembly38.known_indels.vcf.gz
    wgs_intervals: 
      checksum: 3d7e610b5dba434a809827931293f2fe
      path: poirot/homo_sapiens.hg38.wgs.interval_list
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/homo_sapiens.hg38.wgs.interval_list
    str_catalog:
      checksum: 9f991de16615366c9195c671d205a440
      path: poirot/config/str_catalog/variant_catalog_hg38.json
      type: file
      url: file:poirot_config/config/str_catalog/variant_catalog_hg38.json
    GRCh38_chromosomes:
      checksum: 9f5c616f44f601bf7be983cc17ead95d
      path: poirot/GRCh38_chromosomes.bed.gz
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GRCh38_chromosomes.bed.gz
    GRCh38_chromosomes_index:
      checksum: 3b115d2350fe850cb051a6133ee3659a
      path: poirot/GRCh38_chromosomes.bed.gz.tbi
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GRCh38_chromosomes.bed.gz.tbi
  
  gnomad_sv_vcf:
    checksum: 16cac79cd6846346396d54ad3c14ef0f
    path: poirot/gnomad.v4.0.sv.vcf.gz
    type: file
    url: file:/data/ref_data/gnomad/gnomad_sv/gnomad.v4.0.sv.vcf.gz
  
  gnomad_sv_vcf_index:
    checksum: b1d41e6310df0597935bd9057b6de740
    path: poirot/gnomad.v4.0.sv.vcf.gz.tbi
    type: file
    url: file:/data/ref_data/gnomad/gnomad_sv/gnomad.v4.0.sv.vcf.gz.tbi

    
  peddy_sites:
    checksum: 736f74618ab09407ffa102bbb6475015
    path: poirot/peddy/v0.4.8/GRCH38.bed
    type: file
    url: file:/beegfs-storage/data/ref_data/peddy/v0.4.8/GRCH38.bed

  svdb_query:
    cnvpytor:
      checksum: f011fcf8b477585a4bc29fe8f74ae8c4 
      path: poirot/svdb_query/cnvpytor_wgs_hg38_1.0.vcf.gz
      type: file
      url: file:/beegfs-storage/data/ref_data/wp3/svdb/svdb_create/cnvpytor_wgs_hg38_1.0.vcf.gz
    manta:
      checksum: f9a964a41ba7545a28b2fe5c000f8310 
      path: poirot/svdb_query/manta_wgs_hg38_1.0.vcf.gz
      type: file
      url: file:/beegfs-storage/data/ref_data/wp3/svdb/svdb_create/manta_wgs_hg38_1.0.vcf.gz
  
  verifybamid:
    mu:
      checksum: e487244f85c53b66865c34b588341e50
      path: poirot/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.mu
      type: file
      url: file:/beegfs-storage/data/ref_data/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.mu
    bed:
      checksum: 689f507dc1f281dfe35880315a5ac19c
      path: poirot/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.bed
      type: file
      url: file:/beegfs-storage/data/ref_data/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.bed
    UD:
      checksum: e93de9cf95d30486606e3f35b381d93c
      path: poirot/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.UD
      type: file
      url: file:/beegfs-storage/data/ref_data/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.UD
    V:
      checksum: 8de3d2e20b6e391e8141829009c1e3e2
      path: poirot/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.V
      type: file
      url: file:/beegfs-storage/data/ref_data/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.V
    

  bwa_mem:
    amb:
      checksum: f84b47b7ec12946b92d9762cec04b835 
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb
    ann:
      checksum: d8a1ff524ec2150c0b9b7e544dc086a6 
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.ann
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.ann
    bwt:
      checksum: 3fce90c2d2c1ea3eafcdcd5f17ec8724
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.bwt
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.bwt
    pac:
      checksum: 586a1236048aa02f47296f799eacc175
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.pac
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.pac
    sa:
      checksum: 678c3326343f00c18ff05aa5e67c090a
      path: poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.sa
      type: file
      url: file:/beegfs-storage/data/ref_genomes/GRCh38/GRCmasked/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.sa
  
