PIPELINE_VERSION: v0.8.0

REFERENCE_DATA: /proj/ngi2024001/nobackup/bin/wp3_hg/design_and_ref_files

APPTAINER_CACHE: /proj/ngi2024001/nobackup/bin/wp3_hg/{{PIPELINE_VERSION}}/apptainer_cache

hydra_local_path: /proj/ngi2024001/nobackup/bin/wp3_hg/{{PIPELINE_VERSION}}/hydra-genetics

aligner: bwa_gpu

snp_caller: deepvariant_gpu

resources: config/resources_production_pipeline.miarka.yaml

samples: samples_with_info.tsv

units: units.tsv

output: config/output_list.json

default_container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.11.1.sif'

modules:
  alignment: v0.6.0
  annotation: v1.0.1
  cnv_sv: v0.5.0
  compression: v2.0.0
  filtering: v0.3.0
  misc: v0.2.0
  mitochondrial: v0.1.0
  parabricks: v1.2.0
  prealignment: v1.2.0
  qc: v0.5.0
  snv_indels: v1.0.0

reference:
  coverage_bed: '{{REFERENCE_DATA}}/poirot/refseq_select_mane_with_MT_with_non_coding_20241010.bed'
  design_bed: '{{REFERENCE_DATA}}/poirot/homo_sapiens.hg38.wgs.bed'
  exome_bed: '{{REFERENCE_DATA}}/poirot/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.bed'
  exome_intervals: '{{REFERENCE_DATA}}/poirot/hg38_exome_comp_spikein_v2.0.2_targets_sorted.re_annotated.sorted.interval_list'
  fai: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.fai'
  fasta: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta'
  genepanels: config/gene_panels/genepanels_WGS.list
  merge_contigs:
  - .*_random
  - chrUn_.*
  - chrEBV
  sites: '{{REFERENCE_DATA}}/poirot/Homo_sapiens_assembly38.known_indels.vcf.gz'
  str_panels:
  - ataxi.list
  - dystoni.list
  - spastisk_paraplegi.list
  str_panels_dir: config/str_panels
  wgs_intervals: '{{REFERENCE_DATA}}/poirot/homo_sapiens.hg38.wgs.interval_list'

trimmer_software: fastp_pe

automap:
  build: hg38
  container: '{{APPTAINER_CACHE}}/hydragenetics__automap_1.2.sif'
  extra: --DP 10 --minsize 3 --chrX
  outdir: cnv_sv/automap

bcftools_split_vep:
  columns: gnomad_AF:Float

bcftools_view_biallelic:
  extra: -m2 -M2 -v snps

bcftools_softfilter_cnvpytor:
  exclude: '''pytorP1>0.0001 | pytorDG<100000 | pytorPN>0.5 | ( pytorQ0>0.5 && FORMAT/CN
    != 0)'''
  extra: '-s LowQual '

bcftools_hardfilter_cnvpytor:
  exclude: '''pytorP1>0.0001 | pytorDG<100000 | pytorPN>0.5 | ( pytorQ0>0.5 && FORMAT/CN
    != 0)'''

bcftools_view_pass:
  extra: '--apply-filter PASS '

bcftools_view_svdb:
  extra: -f 'PASS' -e 'manta_AF>0.05 | cnvpytor_AF>0.05 | gnomad_AF>0.1'

bwa_mem:
  amb: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.amb'
  ann: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.ann'
  bwt: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.bwt'
  container: '{{APPTAINER_CACHE}}/hydragenetics__bwa_0.7.15.sif'
  pac: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.pac'
  sa: '{{REFERENCE_DATA}}/poirot/GCA_000001405.15_GRCh38_no_alt_analysis_set_GRCmasked.fasta.sa'

bwa_mem_mito:
  amb:
    mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.amb'
    mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.amb'
  ann:
    mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.ann'
    mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.ann'
  bwt:
    mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.bwt'
    mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.bwt'
  container: '{{APPTAINER_CACHE}}/hydragenetics__bwa_mem_0.7.17.sif'
  extra: '-K 100000000 -v3 -Y '
  pac:
    mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.pac'
    mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.pac'
  sa:
    mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta.sa'
    mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta.sa'

cnvpytor_readdepth:
  container: '{{APPTAINER_CACHE}}/hydragenetics__cnvpytor_1.3.1.sif'
  extra: '-chrom chr1 chr2 chr3 chr4 chr5 chr6 chr7 chr8 chr9 chr10 chr11 chr12 chr13
    chr14 chr15 chr16 chr17 chr18 chr19 chr20 chr21 chr22 chrX chrY chrM '
  length_list: '500'

cnvpytor_filter:
  Q0_range: -1 0.5
  calling_model: rd_mean_shift
  container: '{{APPTAINER_CACHE}}/hydragenetics__cnvpytor_1.3.1.sif'
  dG_range: 100000 inf
  pN_range: 0 0.5
  p_range: 0 0.0001
  view: '500'

create_cov_excel:
  container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.11.1.sif'
  covLimits: 10 20 30

deepvariant:
  container: '{{APPTAINER_CACHE}}/google__deepvariant_1.6.1.sif'
  model_type: WGS
  output_gvcf: true

expansionhunter:
  container: '{{APPTAINER_CACHE}}/hydragenetics__expansionhunter_5.0.0.sif'
  variant_catalog: config/str_catalog/variant_catalog_hg38.json

fastp_pe:
  container: '{{APPTAINER_CACHE}}/hydragenetics__fastp_0.20.1.sif'
  extra: --trim_poly_g --qualified_quality_phred 15 --unqualified_percent_limit 40
    --n_base_limit 5 --length_required 15

fastqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics__fastqc_0.11.9.sif'

filter_vcf:
  germline: config/config_hard_filter_germline.yaml

gatk_collect_wgs_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'
  coverage_cap: 100000
  read_length: 151

gatk_filter_contamination:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_filter_mutect_calls_mt:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_left_align_and_trim_variants:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_lift_over_vcf:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'
  shift_back_chain: '{{REFERENCE_DATA}}/poirot/gatk_mito/ShiftBack.chain'

gatk_mark_duplicates:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_merge_bam_alignment:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_merge_vcfs:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_merge_stats:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_mutect2:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'
  interval:
    mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/non_control_region.chrM.interval_list'
    mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/control_region_shifted.chrM.interval_list'
  max_reads_per_alignment_start: 75

gatk_print_reads:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'
  interval: chrM

gatk_revert_sam:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_sam_to_fastq:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_select_variants:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_sort_sam:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_split_multi_allelic_sites:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

gatk_variant_filtration:
  container: '{{APPTAINER_CACHE}}/hydragenetics__gatk4_4.2.2.0.sif'

glnexus_trio:
  configfile: DeepVariantWGS
  container: '{{APPTAINER_CACHE}}/ghcr.io__dnanexus-rnd__glnexus_v1.4.1.sif'

glnexus_peddy:
  configfile: DeepVariantWGS
  container: '{{APPTAINER_CACHE}}/ghcr.io__dnanexus-rnd__glnexus_v1.4.1.sif'
  extra: '--bed {{REFERENCE_DATA}}/poirot/peddy/v0.4.8/GRCH38.bed '

haplocheck:
  container: '{{APPTAINER_CACHE}}/hydragenetics__haplocheck_1.3.3.sif'

manta_config_n:
  container: '{{APPTAINER_CACHE}}/hydragenetics__manta_1.6.0.sif'
  extra: --callRegions {{REFERENCE_DATA}}/poirot/GRCh38_chromosomes.bed.gz

manta_run_workflow_n:
  container: '{{APPTAINER_CACHE}}/hydragenetics__manta_1.6.0.sif'

mosdepth:
  by: '500'
  container: '{{APPTAINER_CACHE}}/hydragenetics__mosdepth_0.3.2.sif'
  extra: '--fast-mode --use-median --no-per-base '

mosdepth_bed:
  container: '{{APPTAINER_CACHE}}/hydragenetics__mosdepth_0.3.2.sif'
  extra: ''

multiqc:
  container: '{{APPTAINER_CACHE}}/hydragenetics__multiqc_1.21.sif'
  reports:
    DNA:
      config: config/multiqc_config_DNA.yaml
      included_unit_types:
      - N
      qc_files:
      - qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq1_fastqc.zip
      - qc/fastqc/{sample}_{type}_{flowcell}_{lane}_{barcode}_fastq2_fastqc.zip
      - qc/mosdepth/{sample}_{type}.mosdepth.summary.txt
      - qc/mosdepth/{sample}_{type}.mosdepth.region.dist.txt
      - qc/mosdepth/{sample}_{type}.mosdepth.global.dist.txt
      - qc/peddy/peddy.peddy.ped
      - qc/peddy/peddy.background_pca.json
      - qc/peddy/peddy.ped_check.csv
      - qc/peddy/peddy.sex_check.csv
      - qc/peddy/peddy.het_check.csv
      - qc/peddy/peddy_sex_check_mqc.tsv
      - qc/peddy/peddy_rel_check_mqc.tsv
      - qc/picard_collect_alignment_summary_metrics/{sample}_{type}.alignment_summary_metrics.txt
      - qc/picard_collect_duplication_metrics/{sample}_{type}.duplication_metrics.txt
      - qc/picard_collect_gc_bias_metrics/{sample}_{type}.gc_bias.summary_metrics
      - qc/picard_collect_hs_metrics/{sample}_{type}.HsMetrics.txt
      - qc/picard_collect_insert_size_metrics/{sample}_{type}.insert_size_metrics.txt
      - qc/picard_collect_wgs_metrics/{sample}_{type}.txt
      - qc/samtools_stats/{sample}_{type}.samtools-stats.txt
      - qc/samtools_idxstats/{sample}_{type}.samtools-idxstats.txt
      - qc/verifybamid2/{sample}_{type}.selfSM

mt_reference:
  blacklist: '{{REFERENCE_DATA}}/poirot/gatk_mito/blacklist_sites.hg38.chrM.bed'
  mt: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.fasta'
  mt_shifted: '{{REFERENCE_DATA}}/poirot/gatk_mito/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta'

pbrun_deepvariant:
  container: '{{APPTAINER_CACHE}}/nvcr.io__nvidia__clara__clara-parabricks_4.3.0-1.sif'
  extra: '--num-cpu-threads-per-stream 5 --num-streams-per-gpu 2 --disable-use-window-selector-model
    --gvcf '
  tmp_dir: /tmp/

pbrun_fq2bam:
  container: '{{APPTAINER_CACHE}}/nvcr.io__nvidia__clara__clara-parabricks_4.3.0-1.sif'
  extra: '--gpusort --gpuwrite --num-cpu-threads-per-stage 10 '
  tmp_dir: /tmp/

peddy:
  config: config/peddy_mqc.yaml
  container: '{{APPTAINER_CACHE}}/hydragenetics__peddy_0.4.8.sif'
  extra: '--sites hg38 '

picard_collect_alignment_summary_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_duplication_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_gc_bias_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_hs_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_insert_size_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_collect_wgs_metrics:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.0.sif'

picard_mark_duplicates:
  container: '{{APPTAINER_CACHE}}/hydragenetics__picard_2.25.4.sif'

reviewer:
  container: '{{APPTAINER_CACHE}}/hydragenetics__reviewer_0.2.7.sif'

samtools_stats:
  container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.11.1.sif'

samtools_idxstats:
  container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.11.1.sif'

samtools:
  container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.11.1.sif'

smn_caller:
  container: '{{APPTAINER_CACHE}}/hydragenetics__smncopynumbercaller_1.1.2.sif'
  genome_version: '38'

smn_charts:
  container: '{{APPTAINER_CACHE}}/hydragenetics__smncopynumbercaller_1.1.2.sif'

spring:
  container: '{{APPTAINER_CACHE}}/hydragenetics__spring_1.1.1.sif'

stranger:
  catalog: config/str_catalog/variant_catalog_hg38.json
  container: '{{APPTAINER_CACHE}}/hydragenetics__stranger_0.8.1.sif'

svdb_merge:
  container: '{{APPTAINER_CACHE}}/hydragenetics__svdb_2.8.2.sif'
  extra: '--pass_only --no_intra '
  overlap: 0.6
  priority: manta,cnvpytor

svdb_query:
  container: '{{APPTAINER_CACHE}}/hydragenetics__svdb_2.8.2.sif'
  db_string: --db {{REFERENCE_DATA}}/poirot/svdb_query/manta_wgs_hg38_1.0.vcf.gz,{{REFERENCE_DATA}}/poirot/svdb_query/cnvpytor_wgs_hg38_1.0.vcf.gz
  extra: '--in_frq FRQ,FRQ --in_occ OCC,OCC --out_frq manta_AF,cnvpytor_AF --out_occ
    manta_OCC,cnvpytor_OCC '

tabix:
  container: '{{APPTAINER_CACHE}}/hydragenetics__common_1.11.1.sif'

tiddit:
  container: '{{APPTAINER_CACHE}}/hydragenetics__tiddit_3.7.0.sif'

upd:
  container: '{{APPTAINER_CACHE}}/hydragenetics__upd_0.1.1.sif'
  extra: '--vep '

vep:
  container: '{{APPTAINER_CACHE}}/ensemblorg__ensembl-vep_release_110.1.sif'
  extra: --assembly GRCh38 --check_existing --pick --sift b --polyphen b --ccds --symbol
    --af --af_1kg --af_gnomad --max_af
  vep_cache: /beegfs-storage/data/ref_genomes/VEP/

vep_trio:
  container: '{{APPTAINER_CACHE}}/ensemblorg__ensembl-vep_release_110.1.sif'
  extra: --assembly GRCh38 --check_existing --pick --max_af --buffer_size 50000
  vep_cache: /beegfs-storage/data/ref_genomes/VEP/

vep_svdb:
  container: '{{APPTAINER_CACHE}}/ensemblorg__ensembl-vep_release_110.1.sif'
  extra: --assembly GRCh38 --check_existing --pick --custom file={{REFERENCE_DATA}}/poirot/gnomad.v4.0.sv.vcf.gz,short_name=gnomad,fields=AF%CN_NONREF_FREQ%FILTER%ALGORITHMS%EVIDENCE%SVTYPE,format=vcf,reciprocal=1,overlap_cutoff=60,distance=1000,same_type=1
  vep_cache: /beegfs-storage/data/ref_genomes/VEP/

verifybamid2:
  container: '{{APPTAINER_CACHE}}/hydragenetics__verifybamid2_2.0.1.sif'
  svd_mu: '{{REFERENCE_DATA}}/poirot/verifybamid2/1000g.phase3.100k.b38.vcf.gz.dat.mu'

vt_decompose:
  container: '{{APPTAINER_CACHE}}/hydragenetics__vt_2015.11.10.sif'

