---

default_resources:
  threads: 1
  time: "12:00:00"
  mem_mb: 6144
  mem_per_cpu: 6144
  partition: "core"

bwa_mem:
  mem_mb: 98304
  mem_per_cpu: 6144
  threads: 16

bwa_mem_merge:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8

bwa_mem_mito:
  mem_mb: 6144
  mem_per_cpu: 3072
  threads: 2

cnvpytor_readdepth:
  mem_mb: 73728
  mem_per_cpu: 6144
  threads: 12
  time: "12:00:00"

cnvpytor_readdepth_combined:
  mem_mb: 73728
  mem_per_cpu: 6144
  threads: 12
  time: "12:00:00"

deepvariant:
  mem_mb: 122880
  mem_per_cpu: 6144
  threads: 24
  time: "20:00:00"

expansionhunter:
  threads: 16
  mem_mb: 98304
  mem_per_cpu: 6144

fastp_pe:
  threads: 8
  mem_mb: 49152
  mem_per_cpu: 6144

fastqc:
  threads: 2
  mem_mb: 12288
  mem_per_cpu: 6144

gatk_mark_duplicates:
  mem_mb: 4096
  mem_per_cpu: 4096

gatk_sam_to_fastq:
  mem_mb: 5120
  mem_per_cpu: 5120

gatk_sort_sam:
  mem_mb: 4096
  mem_per_cpu: 4096

gatk_mark_duplicates:
  mem_mb: 4096
  mem_per_cpu: 4096

gatk_sam_to_fastq:
  mem_mb: 5120
  mem_per_cpu: 5120

gatk_sort_sam:
  mem_mb: 4096
  mem_per_cpu: 4096

glnexus:
  mem_mb: 196608
  threads: 24

manta_run_workflow_n:
  threads: 24
  mem_mb: 147456
  mem_per_cpu: 6144

melt:
  mem_mb: 40960
  mem_per_cpu: 4096
  threads: 10

mosdepth:
  mem_mb: 36864
  threads: 4

mosdepth_bed:
  mem_mb: 36864
  threads: 4

pbrun_fq2bam:
  gres: "--gres=gres:gpu:l40s:6"
  mem_mb: 360000
  partition: "gpu"
  mem_per_cpu: 5000
  threads: 64
  time: "02:00:00"

pbrun_deepvariant:
  gres: "--gres=gres:gpu:a100:4"
  mem_mb: 480000
  mem_per_cpu: 5000
  partition: "gpu"
  threads: 96
  time: "02:00:00"

peddy:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8

samtools_stats:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8

samtools_idxstats:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8

samtools_merge_bam:
  mem_mb: 73728
  mem_per_cpu: 6144
  threads: 12

samtools_sort:
  mem_mb: 73728
  mem_per_cpu: 6144
  threads: 12

samtools_view:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8
  
smn_caller:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8

spring:
  mem_mb: 49152
  mem_per_cpu: 6144
  threads: 8

tiddit:
  threads: 8
  mem_mb: 49152
  mem_per_cpu: 6144
  time: "20:00:00"

vep:
  mem_mb: 24576
  mem_per_cpu: 6144
  threads: 4  
